# Composer original de tronyx:
# https://github.com/tronyx?tab=repositories
# https://github.com/tronyx/Docker-Nagios
# Usuario: nagiosadmin
# Passwd: nagios

version: '3.2'
services:
  nagios:
    image: tronyx/nagios
    ports:
      - 80:80/tcp
    volumes:
    #  /path-to-nagios/etc/:/opt/nagios/etc/
    #  /path-to-nagios/var:/opt/nagios/var/
    #  /path-to-custom-plugins:/opt/Custom-Nagios-Plugins
    #  /path-to-nagiosgraph-var:/opt/nagiosgraph/var
    #  /path-to-nagiosgraph-etc:/opt/nagiosgraph/etc
      - nagios-etc:/opt/nagios/etc/
      - nagios-var:/opt/nagios/var/
      - nagios-custom-plugins:/opt/Custom-Nagios-Plugins
      - nagiosgraph-etc:/opt/nagiosgraph/etc
      - nagiosgraph-var:/opt/nagiosgraph/var

# volumes:
  nagios-etc:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/swarm-data/nagios/etc
  nagios-var:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/swarm-data/nagios/var
  nagios-custom-plugins:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/swarm-data/nagios/custom-plugins
  nagiosgraph-etc:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/swarm-data/nagiosgraph/etc
  nagiosgraph-var:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/swarm-data/nagiosgraph/var