# https://nginxproxymanager.com/setup/
# https://github.com/NginxProxyManager/nginx-proxy-manager
# Credenciales por defecto
# Email: admin@example.com
# Password: changeme

version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      DISABLE_IPV6: 'true'
    volumes:
      # Cambio la ubicacion de los directorios
      - /home/swarm-data/npm/data:/data
      - /home/swarm-data/npm/le:/etc/letsencrypt
    depends_on:
      - db
    # Como estoy trabajando con docker swarm le fuerzo que se haga el contenedor en un nodo worker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      # Cambio la ubicacion de los directorios
      - /home/swarm-data/npm/db:/var/lib/mysql
    # Como estoy trabajando con docker swarm le fuerzo que se haga el contenedor en un nodo worker
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == worker]
networks:
  default:
    driver: overlay