# https://nginxproxymanager.com/setup/
# https://github.com/NginxProxyManager/nginx-proxy-manager
version: '3.7'
# Credenciales por defecto
# Email: admin@example.com
# Password: changeme

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
#      - ./data:/data
#      - ./letsencrypt:/etc/letsencrypt
      - npm_data:/data
      - npm_le:/etc/letsencrypt
    depends_on:
      - db

  db:
#    image: 'jc21/mariadb-aria:latest'
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
#      - ./mysql:/var/lib/mysql
      - npm_db:/var/lib/mysql
volumes:
  npm_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /swarm-data/npm/data
  npm_le:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /swarm-data/npm/le
  npm_db:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /swarm-data/npm/db