version: '3.7'

services:
    db:
      image: mariadb:latest
      deploy:
        mode: replicated
        replicas: 1
        placement:
          preferences:
            - spread: node.labels.zone
          constraints:
            - node.role == worker
      volumes:
        - wp_db:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: MYSQL_PASSWORD
        MYSQL_DATABASE: wordpress
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
    wordpress:
      image: wordpress:latest
      deploy:
        mode: replicated
        replicas: 1
        placement:
          preferences:
            - spread: node.labels.zone
          constraints:
            - node.role == worker
      volumes:
        - wp_data:/var/www/html
      ports:
        - 80:80
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
volumes:
  wp_db:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /swarm-data/wordpress/db
  wp_data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /swarm-data/wordpress/data
