# Generated by Django 5.0.6 on 2024-06-13 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=100)),
                ('Equipo', models.CharField(max_length=100)),
                ('Serie', models.CharField(max_length=100, unique=1)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('Microprocesador', models.CharField(blank=True, max_length=100, null=True)),
                ('MemoriaRam', models.CharField(blank=True, max_length=100, null=True)),
                ('Disco', models.CharField(blank=True, max_length=100, null=True)),
                ('PlacaGrafica', models.CharField(blank=True, max_length=100, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.sucursal')),
            ],
        ),
    ]
