# Generated by Django 5.0.6 on 2024-06-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursal'},
        ),
        migrations.AddField(
            model_name='equipo',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
