# Generated by Django 5.0.6 on 2024-06-19 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_alter_sucursal_options_equipo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Ip', models.GenericIPAddressField()),
                ('MacAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='estado',
            new_name='Estado',
        ),
        migrations.CreateModel(
            name='ImpresoraAsignadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.equipo')),
                ('Impresora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='systems.impresora')),
            ],
        ),
    ]
