# Generated by Django 5.0.6 on 2024-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_impresora_rename_estado_equipo_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='Modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
