# Generated by Django 5.0.6 on 2024-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_impresora_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='Discoserie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='Marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='SO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
