# Generated by Django 5.0.6 on 2024-06-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0009_equipo_ip_equipo_monitorsn_1_equipo_monitorsn_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='Correo',
            field=models.ManyToManyField(blank=True, null=True, to='systems.correos'),
        ),
    ]
