# Generated by Django 5.0.6 on 2024-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_correos_equipo_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Correo',
            field=models.ManyToManyField(blank=True, to='systems.correos'),
        ),
    ]
