# Generated by Django 5.0.6 on 2024-07-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0014_alter_correos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='Empresa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
