# Generated by Django 5.0.6 on 2024-07-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0015_impresora_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='Empresa',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
