# COMPROBADO
# https://docs.portainer.io/start/install-ce/server/swarm/linux -> Comunity Edition
# https://docs.portainer.io/start/install/server/swarm/linux -> Business Edition
# https://docker-ip:9443/

version: '3.8'

services:
  portainer:
    # Confiuracion del dock
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    # Configuracion de puertos
    ports:
      - "9000:9000"
      - "9443:9443"
      - "8000:8000"
    # Configuracion de discos
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
# Como hago uso de los volumenes aca hago las declaraciones
volumes:
  # Volumen ara guardar los datos de Portainer
  portainer-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /mnt/docker-data/portainer-data
      o: bind
    name: portainer-data
    scope: local
