# COMPROBADO
# https://docs.portainer.io/start/install-ce/server/swarm/linux -> Comunity Edition
# https://docs.portainer.io/start/install/server/swarm/linux -> Business Edition
# https://docker-ip:9443/

version: '3.8'

services:
  portainer:
    # Confiuracion del dock
    container_name: portainer
    image: portainer/portainer-ce:latest
    # Configuracion de puertos
    ports:
      - "9000:9000"
      - "9443:9443"
      - "8000:8000"
    restart: always
    # Configuracion de discos
    volumes:
      - ./volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
