# COMPROBADO
# https://iesgn.github.io/curso_docker_2021/sesion5/wordpress.html
# Creado teniendo en cuenta que esta funcionando el stack portainer + mariadb
# + phpmyadmin + nginx-proxy-manager, por lo que el servidor mariadb ya esta creado
# primero tenemos que crear las credenciales con phpmyadmin

version: '3.8'

services:
  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # Como esta configurado con otra red no se le mapean los puertos
    # ports:
      # - 80:80
    volumes:
      - wordpress-data:/var/www/html # /wp-content
    # Configuramos una IP estatica para el dock en la red portainer
    hostname: wordpress
    networks:
      lan_docker:

networks:
  lan_docker:
    external: true

# Como hago uso de los volumenes aca hago las declaraciones
# Es muy importante que los directorios existan para que el stack funcione
volumes:
  # Volumen ara guardar los datos de Portainer
  wordpress-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /mnt/docker-data/wordpress-data
      o: bind
    name: wordpress-data

# Como ya tengo DB comento para dejar la configuracion original
#  db:
#    container_name: servidor_mysql
#    image: mariadb
#    restart: always
#    environment:
#      MYSQL_DATABASE: bd_wp
#      MYSQL_USER: user_wp
#      MYSQL_PASSWORD: asdasd
#      MYSQL_ROOT_PASSWORD: asdasd
#    volumes:
#      - mariadb_data:/var/lib/mysql
#volumes:
#    wordpress_data:
#    mariadb_data: