# Lo saque del servidor de sitios de Strong

services:
  wordpress:
    depends_on:
      - 'db'
    image: 'wordpress:latest'
    container_name: '${CON_WP_NAME}'
    ports:
      - '${EXTERNAL_PORT}:80'
    restart: 'always'
    environment:
      WORDPRESS_DB_HOST: 'db:${MYSQL_PORT}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
    volumes:
      - '/contenedores/wp-sites/${DOMAIN}/wp-content:/var/www/html'
      - '/contenedores/wp-sites/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini'
      
  db:
    image: 'mariadb:latest'
    container_name: '${CON_DB_NAME}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_DB_PASSWORD}'
      MYSQL_TCP_PORT: '${MYSQL_PORT}'
    volumes:
      - '/contenedores/wp-sites/${DOMAIN}/mysql-data/db_data:/var/lib/mysql'
      - '/contenedores/wp-sites/${DOMAIN}/mysql-conf.d:/etc/mysql/conf.d'

