# COMPROBADO
# Stack para habilitar el monitoreo en un servidor grafana ya funcionando
# Al igual que otros stacks esta con la configurcion de IP fija
# https://grafana.com/grafana/dashboards/893-main/
# https://github.com/google/cadvisor

version: '3.8'
services:
  # Con esto vamos a obtener informacion de la maquina
  # https://github.com/prometheus/node_exporter
  # https://prometheus.io/docs/guides/node-exporter/
  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9100:9100'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: node-exporter
    networks:
      lan_docker:

  # Con esto vamos a obtener informacion de la pagina web
  # https://github.com/prometheus/blackbox_exporter
  # https://github.com/prometheus-community/prometheus-playground/blob/master/blackbox-exporter/docker-compose.yml
  blackbox-exporter:
    container_name: blackbox-exporter
    image: prom/blackbox-exporter:latest
    restart: unless-stopped
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '9115:9115'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: blackbox-exporter
    networks:
      lan_docker:

  # Este contenedor es el que va a monitoreear docker
  # https://prometheus.io/docs/guides/cadvisor/#docker-compose-configuration
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor #google/cadvisor:latest
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # Para que se pueda conectar tenemos que exponer el puerto
    ports:
      - '8080:8080'
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: cadvisor
    networks:
      lan_docker:

# Declaramos la red que vamos a utilizar
networks:
  # Configuracion de la red lan_docker
  lan_docker:
    external: true
