# COMPROBADO
# Base de datos para utilizar con grafana, sirve para recolectar datos de varias fuentes

# https://prometheus.io/docs/prometheus/latest/installation/

version: '3.8'

services:
  # https://docker-ip:9090/
  prometheus:
    # Confiuracion del dock
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      # Configuracion de puertos, no se declara puertos ya que no hace falta por la configuracion de la red y NPM
    # ports:
      # - "9090:9090"
    restart: always

    # Configuracion de discos
    # Es muy importante que los directorios existan para que el stack funcione
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    # Le doy un nombre al stack para referirlo con NPM y le damos la red correspondiente
    hostname: prometheus
    networks:
      lan_docker:

# Declaramos la red que vamos a utilizar
networks:
  # Configuracion de la red lan_docker
  lan_docker:
    external: true

# Como hago uso de los volumenes aca hago las declaraciones
# Es muy importante que los directorios existan para que el stack funcione
volumes:
  # Volumen ara guardar la configuracion
  prometheus-config:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /mnt/docker-data/prometheus/config
      o: bind
    name: prometheus-config
  # Volumen ara guardar los datos de prometheus
  prometheus-data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: /mnt/docker-data/prometheus
      o: bind
    name: prometheus-data
